"use client";
import * as React from 'react';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Select } from '@/components/ui/select';

function useCommunitySettings() {
  const [loading, setLoading] = React.useState(true);
  const [data, setData] = React.useState<any>(null);
  const [error, setError] = React.useState<string | null>(null);
  React.useEffect(() => {
    (async () => {
      try {
        const res = await fetch('/api/community/settings', { cache: 'no-store' });
        const json = await res.json();
        if (!res.ok) throw new Error(json.error || 'Failed to load');
        setData(json.data);
      } catch (e:any) {
        setError(e.message);
      } finally {
        setLoading(false);
      }
    })();
  }, []);
  return { loading, data, error, setData };
}

export default function CommunitySettingsPage() {
  const { loading, data, setData, error } = useCommunitySettings();
  const [saving, setSaving] = React.useState(false);
  const [launched, setLaunched] = React.useState(false);
  const [copied, setCopied] = React.useState(false);

  const [form, setForm] = React.useState({
    slug: data?.slug || '',
    name: data?.name || '',
    description: data?.description || '',
    youtube_url: data?.youtube_url || '',
    feature1: data?.feature1 || '',
    feature2: data?.feature2 || '',
    feature3: data?.feature3 || '',
    price_cents: data?.price_cents || 0,
    currency: data?.currency || 'usd',
    billing_interval: data?.billing_interval || 'one_time',
  });

  React.useEffect(() => {
    if (data) {
      setForm({
        slug: data.slug || '',
        name: data.name || '',
        description: data.description || '',
        youtube_url: data.youtube_url || '',
        feature1: data.feature1 || '',
        feature2: data.feature2 || '',
        feature3: data.feature3 || '',
        price_cents: data.price_cents || 0,
        currency: data.currency || 'usd',
        billing_interval: data.billing_interval || 'one_time',
      });
    }
  }, [data]);

  async function save() {
    setSaving(true);
    try {
      const res = await fetch('/api/community/settings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({
        ...form,
        price_cents: Number(form.price_cents) || 0,
      })});
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || 'Failed to save');
      setData(json.data);
    } catch (e:any) {
      alert(e.message);
    } finally {
      setSaving(false);
    }
  }

  const publicUrl = form.slug ? `/join/${encodeURIComponent(form.slug)}` : '';
  const fullPublicUrl = publicUrl ? `${typeof window !== 'undefined' ? window.location.origin : ''}${publicUrl}` : '';

  // Auto-generate slug when name changes (only if slug is empty or auto-generated)
  const [slugAutoGenerated, setSlugAutoGenerated] = React.useState(true);
  
  React.useEffect(() => {
    if (form.name && slugAutoGenerated) {
      const autoSlug = form.name.toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
      setForm(f => ({ ...f, slug: autoSlug }));
    }
  }, [form.name, slugAutoGenerated]);

  async function copyToClipboard() {
    if (fullPublicUrl) {
      try {
        await navigator.clipboard.writeText(fullPublicUrl);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch (err) {
        // Fallback for older browsers
        const textArea = document.createElement('textarea');
        textArea.value = fullPublicUrl;
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand('copy');
        document.body.removeChild(textArea);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }
    }
  }

  async function launchCommunity() {
    setSaving(true);
    try {
      const res = await fetch('/api/community/settings', { 
        method: 'POST', 
        headers: { 'Content-Type': 'application/json' }, 
        body: JSON.stringify({
          ...form,
          price_cents: Number(form.price_cents) || 0,
        })
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || 'Failed to save');
      setData(json.data);
      setLaunched(true);
    } catch (e: any) {
      alert(e.message);
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4 space-y-8">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-semibold text-gray-900">Create Your Community</h1>
            <p className="text-gray-600 mt-1">Set up your community page and get a shareable link</p>
          </div>
        {fullPublicUrl && !launched && (
          <a href={publicUrl} target="_blank" className="text-sm text-blue-600 hover:text-blue-700 underline">Preview page</a>
        )}
      </div>

      {launched && fullPublicUrl && (
        <div className="bg-green-50 border border-green-200 rounded-lg p-6 space-y-4">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-green-600 rounded-full flex items-center justify-center">
              <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            </div>
            <h3 className="text-lg font-semibold text-green-900">Community Launched Successfully! 🎉</h3>
          </div>
          <p className="text-green-800">Your community page is live and ready to share with your audience.</p>
          
          <div className="bg-white border border-green-200 rounded-md p-3">
            <div className="text-sm text-green-700 mb-2">Your shareable link:</div>
            <div className="flex items-center gap-2">
              <code className="flex-1 text-sm bg-green-50 px-3 py-2 rounded border text-green-800 font-mono">
                {fullPublicUrl}
              </code>
              <Button 
                onClick={copyToClipboard}
                className="bg-green-600 hover:bg-green-700 text-white"
                size="sm"
              >
                {copied ? 'Copied!' : 'Copy'}
              </Button>
              <a 
                href={publicUrl} 
                target="_blank"
                className="inline-flex items-center px-3 py-2 text-sm bg-green-600 hover:bg-green-700 text-white rounded-md"
              >
                View Live Page
              </a>
            </div>
          </div>
          
          <div className="flex gap-2 pt-2">
            <Button 
              onClick={() => setLaunched(false)} 
              variant="outline"
              className="border-green-300 text-green-700 hover:bg-green-50"
            >
              Make Changes
            </Button>
          </div>
        </div>
      )}

        {loading ? (
          <div className="text-sm text-gray-600 bg-white p-6 rounded-lg border border-gray-200">Loading...</div>
        ) : (
        <form className="space-y-6" onSubmit={(e)=>{e.preventDefault(); launchCommunity();}}>
          <div className="bg-white border border-gray-200 rounded-lg p-6 space-y-6">
            <h2 className="text-xl font-semibold text-gray-900">Community Details</h2>
            
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div>
                <Label htmlFor="name" className="text-gray-700 font-medium">Community Name *</Label>
                <Input 
                  id="name" 
                  value={form.name} 
                  onChange={e => {
                    setForm(f=>({...f, name: e.target.value}));
                  }}
                  placeholder="Master the Markets with The Alchemy" 
                  className="mt-1 border-gray-300 text-gray-900 bg-white"
                />
              </div>
              <div>
                <Label htmlFor="slug" className="text-gray-700 font-medium">URL Slug</Label>
                <Input 
                  id="slug" 
                  value={form.slug} 
                  onChange={e => {
                    setSlugAutoGenerated(false);
                    setForm(f=>({...f, slug: e.target.value}));
                  }}
                  placeholder="auto-generated from name" 
                  className="mt-1 border-gray-300 text-gray-900 bg-white"
                />
                <div className="text-xs text-gray-600 mt-1">
                  {publicUrl ? `Your URL: ${publicUrl}` : 'URL will be generated automatically'}
                </div>
              </div>
            </div>

            <div>
              <Label htmlFor="description" className="text-gray-700 font-medium">Description</Label>
              <textarea 
                id="description"
                rows={3}
                value={form.description} 
                onChange={e=>setForm(f=>({...f, description: e.target.value}))} 
                placeholder="Describe what your community offers and why people should join..."
                className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-gray-900 bg-white"
              />
            </div>

            <div>
              <Label htmlFor="youtube" className="text-gray-700 font-medium">YouTube Video URL</Label>
              <Input 
                id="youtube" 
                value={form.youtube_url} 
                onChange={e=>setForm(f=>({...f, youtube_url: e.target.value}))} 
                placeholder="https://www.youtube.com/watch?v=..." 
                className="mt-1 border-gray-300 text-gray-900 bg-white"
              />
              <div className="text-xs text-gray-600 mt-1">Optional: Add a video to showcase your community</div>
            </div>
          </div>

          <div className="bg-white border border-gray-200 rounded-lg p-6 space-y-6">
            <h2 className="text-xl font-semibold text-gray-900">Community Features</h2>
            <p className="text-sm text-gray-600">List the key benefits members will get</p>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <Label htmlFor="f1" className="text-gray-700 font-medium">Feature 1</Label>
                <Input id="f1" value={form.feature1} onChange={e=>setForm(f=>({...f, feature1: e.target.value}))} placeholder="Education Course Content" className="mt-1 border-gray-300 text-gray-900 bg-white" />
              </div>
              <div>
                <Label htmlFor="f2" className="text-gray-700 font-medium">Feature 2</Label>
                <Input id="f2" value={form.feature2} onChange={e=>setForm(f=>({...f, feature2: e.target.value}))} placeholder="Market Analysis & Trading Insights" className="mt-1 border-gray-300 text-gray-900 bg-white" />
              </div>
              <div>
                <Label htmlFor="f3" className="text-gray-700 font-medium">Feature 3</Label>
                <Input id="f3" value={form.feature3} onChange={e=>setForm(f=>({...f, feature3: e.target.value}))} placeholder="Automated System + Proof of Concept" className="mt-1 border-gray-300 text-gray-900 bg-white" />
              </div>
            </div>
          </div>

          <div className="bg-white border border-gray-200 rounded-lg p-6 space-y-6">
            <h2 className="text-xl font-semibold text-gray-900">Pricing</h2>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <Label htmlFor="price" className="text-gray-700 font-medium">Price *</Label>
                <Input 
                  id="price" 
                  type="number" 
                  min={0} 
                  value={Math.round((Number(form.price_cents)||0)/100)} 
                  onChange={e=>setForm(f=>({...f, price_cents: Math.max(0, Math.floor(Number(e.target.value)||0)*100)}))} 
                  placeholder="1599"
                  className="mt-1 border-gray-300 text-gray-900 bg-white"
                />
                <div className="text-xs text-gray-600 mt-1">Amount in {form.currency.toUpperCase()}</div>
              </div>
              <div>
                <Label htmlFor="currency" className="text-gray-700 font-medium">Currency</Label>
                <Input 
                  id="currency" 
                  value={form.currency} 
                  onChange={e=>setForm(f=>({...f, currency: e.target.value.toLowerCase()}))} 
                  placeholder="usd" 
                  className="mt-1 border-gray-300 text-gray-900 bg-white"
                />
              </div>
              <div>
                <Label htmlFor="interval" className="text-gray-700 font-medium">Billing</Label>
                <select 
                  id="interval" 
                  className="mt-1 w-full h-10 border border-gray-300 rounded-md px-3 text-sm bg-white text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500" 
                  value={form.billing_interval} 
                  onChange={e=>setForm(f=>({...f, billing_interval: e.target.value as any}))}
                >
                  <option value="one_time">One-time payment</option>
                  <option value="month">Monthly subscription</option>
                </select>
              </div>
            </div>
          </div>

          <div className="flex justify-center pt-4">
            <Button 
              type="submit" 
              disabled={saving || !form.name.trim()}
              size="lg"
              className="px-8 py-3 text-lg bg-blue-600 hover:bg-blue-700 text-white font-semibold"
            >
              {saving ? 'Launching...' : '🚀 Launch Community'}
            </Button>
          </div>
          </form>
        )}
      </div>
    </div>
  );
}
